create table if not exists relay_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter publication supabase_realtime add table relay_events;
